name: MCPyViewer
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12.1
  - packaging    
  - matplotlib
  - pandas
  - r-base=4.3.1
  - r-biocmanager
  - bioconductor-biomart
  - bioconductor-gviz
  - r-dplyr
  - r-readr
  - r-ggplot2
  - r-reshape2
  - r-optparse
  - r-lattice
  - r-ggrepel
  - r-tidyr
  - r-cowplot
  - r-circlize
  - r-stringr
  - r-rcolorbrewer
    #  - r-gviz=1.46.1
    #  - r-biomart=2.58.2
  - r-dbplyr=2.3.4
  - bwa=0.7.17
  - samtools=1.21
  - picard=3.0.0
